---
- name: Create Splunk group
  ansible.builtin.group:
    name: "{{ splunk_forwarder_group }}"
    gid: "{{ splunk_forwarder_gid }}"
    state: present
  tags: splunk_user

- name: Create Splunk user
  ansible.builtin.user:
    name: "{{ splunk_forwarder_user }}"
    group: "{{ splunk_forwarder_group }}"
    uid: "{{ splunk_forwarder_uid }}"
    state: present
  tags: splunk_user

- name: download RPM from Splunk.
  get_url:
      url: "{{ splunk_rpm }}"
      dest: /tmp/
  delegate_to: 127.0.0.1
  become: false
- name: Copy the Splunk Forwarder RPM to remote Servers.
  copy:
      src: /tmp/{{ splunk_forwarder_rpm }}
      dest: ~/{{ splunk_forwarder_rpm }}
      owner: ansible
      group: ansible
      mode: 0644
- name: Install Splunk Forwarder RPM package on remote servers.
  yum:
     name:
       - python3-pexpect.noarch
       - ~/{{ splunk_forwarder_rpm }}
     state: present

- name: Copy the Splunk Forwarder config from your centralized server to remote servers.
  copy:
     src: /tmp/splunk_forwarder_output/
     dest: /opt/splunkforwarder/etc/system/
     directory_mode: yes
     owner: splunk
     group: splunk
     mode: 0600

- name: Copy user seeds file
  ansible.builtin.template:
    src: user-seed.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/user-seed.conf
    mode: 0664
    backup: true
  when: splunk_forwarder_admin_user is defined and splunk_forwarder_admin_pass is defined
  tags: config_copy

- name: Copy deploymentclient file
  ansible.builtin.template:
    src: deploymentclient.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/deploymentclient.conf
    mode: 0664
    backup: true
  when: splunk_forwarder_depl_server is defined
  tags: config_copy

- name: Copy inputs file
  ansible.builtin.template:
    src: inputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/inputs.conf
    mode: 0664
    backup: true
  tags: config_copy

- name: Copy outputs file
  ansible.builtin.template:
    src: outputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    mode: 0664
    backup: true
  tags: config_copy

- name: Upload Splunk Systemd Script
  ansible.builtin.template:
    src: splunkd.service.j2
    dest: /etc/systemd/system/splunkd.service
    owner: root
    group: root
    mode: 0644
  notify: Enable Splunk Forwarder
  when: ansible_service_mgr == 'systemd'
...
